import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generatePDF(record, statusOptions) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const status = statusOptions.find(s => s.value === record.status)
  doc.setFontSize(20); doc.setFont('helvetica', 'bold'); doc.text('MediLog', 20, 22)
  doc.setFontSize(11); doc.setFont('helvetica', 'normal'); doc.setTextColor(120, 114, 104)
  doc.text('Medical Visit Record', 20, 30)
  doc.setDrawColor(216, 208, 196); doc.line(20, 34, 190, 34)
  const basicRows = [['Visit Date', record.visitDate||'-'],['Hospital / Clinic', record.hospital||'-'],['Department', record.department||'-'],['Doctor', record.doctor||'-'],['Status', status?.label||'-'],['Next Visit', record.nextVisitDate||'-']]
  autoTable(doc, { startY: 38, head: [['Field','Details']], body: basicRows, theme: 'grid', headStyles: { fillColor: [184,92,56], textColor: 255, fontStyle: 'bold', fontSize: 10 }, bodyStyles: { fontSize: 10, textColor: [26,23,20] }, columnStyles: { 0: { cellWidth: 45, fontStyle: 'bold', textColor: [107,99,90] } }, margin: { left: 20, right: 20 } })
  const contentFields = [['Chief Complaint',record.chiefComplaint],['Diagnosis',record.diagnosis],['Treatment',record.treatment],['Medications',record.medications],['Lab / Exam Results',record.labResults],['Notes',record.notes]].filter(([,v])=>v)
  if (contentFields.length > 0) { autoTable(doc, { startY: doc.lastAutoTable.finalY+8, head: [['Clinical Details','']], body: contentFields, theme: 'grid', headStyles: { fillColor: [107,143,113], textColor: 255, fontStyle: 'bold', fontSize: 10 }, bodyStyles: { fontSize: 10, textColor: [26,23,20] }, columnStyles: { 0: { cellWidth: 45, fontStyle: 'bold', textColor: [107,99,90] } }, margin: { left: 20, right: 20 } }) }
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(9); doc.setTextColor(150)
  doc.text(`Generated by MediLog · ${new Date().toLocaleDateString('zh-TW')}`, 20, pageHeight - 12)
  doc.save(`MediLog_${record.hospital}_${record.visitDate}.pdf`.replace(/\s/g,'_'))
}
